spring:
  datasource:
    url: jdbc:sqlserver://bial-airport-server.database.windows.net:1433;database=bial-database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: bial-airport-server
    password: AccessDenied123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191